# This is a basic workflow to help you get started with Actions

name: CI-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test:
      name: Test code
      runs-on: ubuntu-latest
      timeout-minutes: 10
      
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
          
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'

        - name: Install dependencies
          run: |
            pip install py_trees
          
        - name: Test with unittest
          run: |
            python -m unittest discover -s ./tests  -p 'test.py'
            python -m unittest discover -s ./robile_safety_features/robile_safety_features -p 'behavior_test.py'
